apiVersion: v1
kind: Service
metadata:
  name: nginx-webui
  namespace: nv-waf-demo
spec:
  selector:
    app: nginx-pod
  ports:
    - port: 80
      name: webui
      protocol: TCP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  namespace: nv-waf-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-pod
          image: nvbeta/swarm_nginx
          ports:
            - containerPort: 80
              protocol: TCP
