apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: nv-waf-demo
spec:
  ports:
    - port: 8888
      protocol: "TCP"
      name: "cluster-tcp-8888"
  selector:
    app: node-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pod
  namespace: nv-waf-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
        - name: node-pod
          image: nvbeta/node
          ports:
            - containerPort: 8888
              protocol: TCP
