apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nv-waf-demo
spec:
  ports:
    - port: 6379
      protocol: "TCP"
      name: "cluster-tcp-6379"
  clusterIP: None
  selector:
    app: redis-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  namespace: nv-waf-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis-pod
          image: redis
          ports:
            - containerPort: 6379
              protocol: TCP
